analyse: arm_types.vhd alu.vhd barrelshift.vhd forwarding.vhd execute.vhd register_file.vhd cache.vhd decode.vhd fetch.vhd memory.vhd writeback.vhd cpu.vhd
        ghdl -a --std=93 -frelaxed-rules --mb-comments --ieee=synopsys -fexplicit arm_types.vhd alu.vhd barrelshift.vhd forwarding.vhd execute.vhd register_file.vhd cache.vhd decode.vhd fetch.vhd memory.vhd writeback.vhd cpu.vhd
